name: Test application

on:
  push:
    branches: [main]
    paths:
      - 'src/'
      - 'public/'
      # - 'scripts/'
      # - 'tests/'
    paths-ignore:
      - 'public/api'
      - 'public/assets/items'
      - 'public/assets/regions'
      - 'public/assets/multiregions'
  pull_request:
    branches: [main]
    paths:
      - 'src/'
      - 'public/'
    paths-ignore:
      - 'public/api'
      - 'public/assets/items'
      - 'public/assets/regions'
      - 'public/assets/multiregions'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Setup python
        run: pip install -r requirements.txt

      - name: Install dependencies
        run: pnpm i && pnpm cypress install && cp .env.github .env

      # - name: Validate scripts
      #   run: pytest -c all-pytest.ini
      #   env:
      #     GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}

      - name: Validate format
        run: pnpm run-p lint

      - name: Validate unit tests
        run: pnpm test:ci

      - name: Build test environment
        run: pnpm build:test-env

      - name: Validate e2e
        run: pnpm test:e2e:ci
