name: Test application

on:
  push:
    branches: [main]
    paths:
      - 'src/'
      - 'public/fixtures'
  pull_request:
    branches: [main]
    paths:
      - 'src/'

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i && pnpm cypress install && cp .env.github .env

      - name: Validate format
        run: pnpm run-p lint

      - name: Validate unit tests
        run: pnpm test:ci

      - name: Build test environment
        run: pnpm build:test-env

      - name: Validate e2e
        run: pnpm test:e2e:ci
