name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i && pnpm cypress install

      - name: Merge catalog entries
        run: pnpm merge-catalog

      - name: Validate app
        run: pnpm run-p lint test:e2e:ci
