name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i && pnpm cypress install && cp .env.github .env

      - name: Merge catalog entries
        run: pnpm merge-catalog

      - name: Validate format
        run: pnpm run-p lint test:ci

      - name: Validate e2e
        uses: cypress-io/github-action@v5.1.0
        timeout-minutes: 10
        with:
          build: pnpm build
          start: pnpm preview:test
          browser: chrome
          record: true
          wait-on: http://localhost:4173/unicef-ai4d-research-bank/
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
