name: Validate catalog items

on:
  pull_request:
    paths:
      - 'catalog/**.yml'

  push:
    branches: [master]
    paths:
      - 'catalog/**.yml'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: python scripts/validate-catalog.py
