name: Validate catalog items

on:
  pull_request:
    paths:
      - 'catalog/**.yml'

  push:
    branches: [main]
    paths:
      - 'catalog/**.yml'

  workflow_dispatch:

jobs:
  validate-catalog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install git-restore-mtime
        run: sudo apt install git-restore-mtime

      - name: Restore mtimes for catalog items
        run: cd catalog && git restore-mtime && cd ../featured && git restore-mtime && cd ../public/api/data && git restore-mtime  && cd ../../..

      - name: Pip install
        run: pip install -r requirements.txt
      - name: Validate Catalog Items
        run: python scripts/validate_catalog.py
        env:
          GSTORAGE_API_KEY: ${{ secrets.GSTORAGE_API_KEY }}
